workflows:
  ios-workflow:
    name: Build iOS IPA
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          cd PokeWalker
          # If no CocoaPods, skip this
          pod install || true
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "PokeWalker.xcodeproj" \
            --scheme "PokeWalker" \
            --export-method development
    artifacts:
      - build/ios/ipa/*.ipa
